---

include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

tox:
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: gdc_test
    POSTGRES_PASSWORD: gdc_test
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
