---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

variables:
  LANGUAGE_VERSION: python3.10

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION:
          - python3.10
          - python3.11
          - python3.12
          - python3.13
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
      variables:
        POSTGRES_DB: automated_test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
        POSTGRES_HOST_AUTH_METHOD: trust
  variables:
    PG_HOST: postgres
