.test:
  variables:
    PY_VERSION:
      description: "The py version with which to run tox e.g. py36"
    DOCKER_IMAGE:
      description: "The image to install for tests"

  image: $DOCKER_IMAGE-bullseye

  before_script:
    # Install postgres
    - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    # Configure postres
    - mkdir /etc/postgresql/13/main/
    - cp travis/postgresql.conf /etc/postgresql/13/main/postgresql.conf
    - cp travis/pg_hba.conf /etc/postgresql/13/main/pg_hba.conf
    - apt update && apt install postgresql-13 postgresql-client-13
    # Install tox & poetry
    - apt-get update && apt-get install -y python3-pip python3-venv
    - /usr/bin/python3.9 -m pipx
    - pipx install poetry
    - pipx install tox
  script:
    - tox -e $PY_VERSION

test:3.6:
  extends:
    - .test
  variables:
    PY_VERSION: py36
    DOCKER_IMAGE: python:3.6

test:3.7:
  extends:
    - .test
  variables:
    PY_VERSION: py37
    DOCKER_IMAGE: python:3.7

test:3.8:
  extends:
    - .test
  variables:
    PY_VERSION: py38
    DOCKER_IMAGE: python:3.8

test:3.9:
  extends:
    - .test
  variables:
    PY_VERSION: py39
    DOCKER_IMAGE: python:3.9

test:3.10:
  extends:
    - .test
  variables:
    PY_VERSION: py310
    DOCKER_IMAGE: python:3.10

test:3.11:
  extends:
    - .test
  variables:
    PY_VERSION: py311
    DOCKER_IMAGE: python:3.11
