.test:
  variables:
    PY_VERSION:
      description: "The py version with which to run tox e.g. py36"
    DOCKER_IMAGE:
      description: "The image to install for tests"

  image: $DOCKER_IMAGE-bullseye

  before_script:
    # Add postgres apt repo
    - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt bullseye-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
    # Install required packages including postgres
    - apt update && apt install -y postgresql-13 postgresql-client-13 python3-pip python3-venv
    # Configure postres
    - export PSQL_CONF_DIR=$(dirname $(psql -t -U postgres -c 'SHOW config_file'))
    - echo $PSQL_CONF_DIR
    - cp travis/postgresql.conf $PSQL_CONF_DIR/postgresql.conf
    - cp travis/pg_hba.conf $PSQL_CONF_DIR/pg_hba.conf
    - service postgresql restart
    - ./psql-users.sh
    # Install universal python commands
    - /usr/bin/python3.9 -m pip install pipx && pipx ensurepath && . ~/.bashrc
    - pipx install poetry
    - pipx inject poetry poetry-dynamic-versioning lockfile
    - pipx install tox
  script:
    - tox -e $PY_VERSION

test:3.6:
  extends:
    - .test
  variables:
    PY_VERSION: py36
    DOCKER_IMAGE: python:3.6

test:3.7:
  extends:
    - .test
  variables:
    PY_VERSION: py37
    DOCKER_IMAGE: python:3.7

test:3.8:
  extends:
    - .test
  variables:
    PY_VERSION: py38
    DOCKER_IMAGE: python:3.8

test:3.9:
  extends:
    - .test
  variables:
    PY_VERSION: py39
    DOCKER_IMAGE: python:3.9

test:3.10:
  extends:
    - .test
  variables:
    PY_VERSION: py310
    DOCKER_IMAGE: python:3.10

test:3.11:
  extends:
    - .test
  variables:
    PY_VERSION: py311
    DOCKER_IMAGE: python:3.11
