---

include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

variables:
  LANGUAGE_VERSION: python3.9

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION: [python3.9, python3.10, python3.11, python3.12, python3.13]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    BASE_CONTAINER_VERSION: 3.1.0
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: gdc_test
    POSTGRES_PASSWORD: gdc_test
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
