---

include:
  - project: nci-gdc/gitlab-templates
    ref: 0.2.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml

tox:
  stage: test
  parallel:
    matrix:
      - BUILD_PY_VERSION: [ 'python3.6', 'python3.7', 'python3.8', 'python3.9' ]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    # these are for postgres docker
    POSTGRES_DB: automated_test
    POSTGRES_USER: gdc_test
    POSTGRES_PASSWORD: gdc_test
    POSTGRES_HOST_AUTH_METHOD: trust
    PG_HOST: postgres
  before_script:
    - !reference [.load_github_key, script]
    - pip install "tox<4"
  script:
    - tox -r -e py


release:
  parallel:
    matrix:
      - RELEASE_PY_VERSION: [ python3.6 ]
  before_script:
    - git fetch --unshallow || true
