[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "GDC models which are outside of the GDC graph"
include = ["gdc_ng_models/alembic/**/*"]
license = "Apache-2.0"
name = "gdc-ng-models"
version = "0.0.0"

[tool.poetry.dependencies]
SQLAlchemy = "^1.4.39"
alembic = {version = "^1.7.0", optional = true}
greenlet = [
  {version = "^1.1.2", python = ">=3.6,<3.11"},
  {version = "2.0.0a2", allow-prereleases = true, python = "^3.11"},
]
psycopg2-binary = "^2.9.3"
python = "^3.6"

[tool.poetry.dev-dependencies]
coverage = [
  {version = "^6.2.0", python = "^3.6"},
  {version = "^6.4.0", python = "^3.7"},
]
pre-commit = "^2.0.0"
pytest = "^7.0.0"
pytz = "^2022.1"

[tool.poetry.extras]
alembic = ["alembic"]

[tool.poetry.scripts]
ng-models = {reference = "bin/ng-models", type = "file"}

[tool.poetry-dynamic-versioning]
dirty = true
enable = true
metadata = true
pattern = "default-unprefixed"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core==1.1.0b2", "poetry-dynamic-versioning"]
