[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=80", "setuptools-scm"]

[dependency-groups]
dev = ["cdisutils", "coverage", "pytest>=6", "pytest-cov", "testcontainers"]

[project]
authors = [
  {name = "GDC feature team", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}
]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14"
]
dependencies = ["psycopg2", "pytz>=2020.5", "sqlalchemy>=1.4.0"]
description = "Non-graph GDC models."
dynamic = ["version"]
keywords = ["Genomic Data Commons", "non-graph-models", "SQLAlchemy", "psqlgraph"]
license = {file = "LICENSE"}
maintainers = [
  {name = "GDC feature team", email = "gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com"}
]
name = "gdc-ng-models"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
alembic = ["alembic>=1.4"]
"sqlalchemy1.4" = ["sqlalchemy~=1.4.0"]
sqlalchemy2 = ["sqlalchemy~=2.0"]

[project.scripts]
ng-models = "gdc_ng_models.cli:main"

[project.urls]
Repository = "https://github.com/NCI-GDC/gdc-ng-models"

[tool.coverage.html]
directory = "docs/htmlcov"
show_contexts = true
title = "gdc-ng-models coverage report"

[tool.coverage.run]
branch = true
context = "tests"
omit = ["*/alembic/*"]
source = ["gdc-ng-models"]

[tool.pytest]
addopts = ["-rfE", "--color=yes", "--cov=gdc_ng_models", "--cov-report=term"]
console_output_style = "classic"
minversion = "6.0"
# Silence warning by opting in to use pytest 6's new default value
junit_family = "xunit2"
junit_logging = "system-out"
log_cli = true
log_cli_level = "INFO"
norecursedirs = [".git", ".tox", "dist", "build"]
testpaths = ["tests/unit", "tests/integration"]

[tool.ruff]
line-length = 95
src = ["src", "tests"]
target-version = "py310" # SET TO THE MINIMUM SUPPORTED VERSION

[tool.ruff.lint]
# see https://docs.astral.sh/ruff/rules/
select = [
  "E", # pydocstyle errors
  "F", # pyflakes
  "I", # isort
  "N", # pep8 naming
  "RUF", # ruff specific rules
  "UP", # pyupgrade
  # "D", # pydocstyle lint
  "W" # pydocstyle warnings
]

[tool.ruff.lint.isort]
known-first-party = ["gdc_ng_models", "tests"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.setuptools_scm]
fallback_version = "0.0.0"

[tool.tox]
env_list = [{product = [{prefix = "py3", start = 10, end = 14}, {sqlalchemy = ["sqlalchemy1.4", "sqlalchemy2"]}]}]

[tool.tox.env_run_base]
commands = [
  ["pytest", {replace = "posargs", default = ["-lv", "--cov-report=xml", "--cov-report=html", "--junit-xml=report.xml"], extend = true}]
]
dependency_groups = ["dev"]
extras = ["{factor:sqlalchemy}"]
pass_env = ["PG_*"]
runner = "uv-venv-lock-runner"

[tool.tox.env_run_base.set_env]
NO_PROXY = "localhost,postgres"
no_proxy = "localhost,postgres"
PG_NAME = "automated_test"
PG_USER = "test"
PG_PASS = "test"

[tool.uv]
conflicts = [[{extra = "sqlalchemy1.4"}, {extra = "sqlalchemy2"}]]

[[tool.uv.index]]
name = "nexus"
url = "https://nexus.osdc.io/repository/pypi-all/simple"
