[metadata]
name = gdc-ng-models
description = Non-graph GDC models
long_description = file: README.md
long_description_content_type = text/markdown
author = Gdc feature team
author_email = gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com
maintainer = GDC Feature Team
maintainer_email = gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com
license = Apache Software License 2.0
license_files = LICENSE
url = https://github.com/NCI-GDC/gdc-ng-models
keywords = Genomic Data Commons, IndexD, REST, indexclient
classifiers =
    License :: OSI Approved :: Apache Software License
    Topic :: Software Development :: Libraries :: Python Modules
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11

[options]
zip_safe = True
packages = find:
package_dir =
    =src
python_requires = >=3.7
include_package_data = True
install_requires =
    psycopg2
    pytz>=2020.5
    sqlalchemy<1.4

[options.packages.find]
where = src

[options.package_data]
gdc_ng_models =
    alembic/*

[options.extras_require]
dev =
    coverage[toml]
    pytest>=6
    pytest-cov
    cdisutils

alembic =
    alembic>=1.4

[options.entry_points]
console_scripts =
    ng-models = gdc_ng_models.cli:main
