[tox]
envlist=py39,py310,py311,py312,py313

[testenv]
passenv =
    PG_*
setenv =
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
deps=
    .[dev]
commands=
    python -m pytest -lv --cov-report xml --cov-report html --junit-xml report.xml {posargs}
runner = virtualenv
