[tox]
envlist=py39,py310,py311,py312,py313

[testenv]
passenv =
    CI
    PG_*
setenv =
    NO_PROXY=localhost,postgres
    no_proxy=localhost,postgres
    PG_NAME=automated_test
    PG_PASS=test
    PG_USER=test
deps=
    .[dev]
commands=
    python -m pytest -lv --cov-report xml --cov-report html --junit-xml report.xml {posargs}
runner = virtualenv
